name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: 'Features'
    labels:
      - 'Type: Enhancement'
  - title: 'Bug Fixes'
    labels:
      - 'Type: Bug'
  - title: 'Maintenance'
    labels:
      - 'Type: Maintenance'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
template: |
  # Changes

  $CHANGES
  
  
  # Contributors
  
  $CONTRIBUTORS
