name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: 'Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: 'Maintenance'
    labels:
      - 'chore'
      - 'refactor'
      - 'clean'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
autolabeler:
  - label: 'chore'
    files:
      - '*.md'
    branch:
      - '/docs{0,1}\/.+/i'
  - label: 'refactor'
    branch:
      - '/refactor\/.+/i'
  - label: 'bug'
    branch:
      - '/fix\/.+/i'
      - '/bug\/.+/i'
      - '/bugfix\/.+/i'
    title:
      - '/fix/i'
  - label: 'enhancement'
    branch:
      - '/features{0,1}\/.+/i'
template: |
  ## Changes

  $CHANGES
  
  
  ## Contributors
  
  $CONTRIBUTORS
