<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Sidekick.Common.Settings\Sidekick.Common.Settings.csproj" />
      <ProjectReference Include="..\Sidekick.Game.Providers\Sidekick.Game.Providers.csproj" />
    </ItemGroup>

</Project>
