//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sidekick.Modules.General.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GeneralResources_ko {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeneralResources_ko() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sidekick.Modules.General.Localization.GeneralResources.ko", typeof(GeneralResources_ko).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 설정한 키로 현재창 닫기.
        /// </summary>
        internal static string EscapeClosesOverlays {
            get {
                return ResourceManager.GetString("EscapeClosesOverlays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 복사한 내용 저장.
        /// </summary>
        internal static string General_RetainClipboard {
            get {
                return ResourceManager.GetString("General_RetainClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 창 닫기.
        /// </summary>
        internal static string Key_Close {
            get {
                return ResourceManager.GetString("Key_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 아이템 찾기.
        /// </summary>
        internal static string Key_FindItems {
            get {
                return ResourceManager.GetString("Key_FindItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Key_Open_In_Craft_Of_Exile {
            get {
                return ResourceManager.GetString("Key_Open_In_Craft_Of_Exile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI 언어.
        /// </summary>
        internal static string Language_UI {
            get {
                return ResourceManager.GetString("Language_UI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MouseWheelNavigateStash {
            get {
                return ResourceManager.GetString("MouseWheelNavigateStash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MouseWheelNavigateStashReverse {
            get {
                return ResourceManager.GetString("MouseWheelNavigateStashReverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 마우스를 클릭해 가격 검색창 닫기.
        /// </summary>
        internal static string OverlayCloseWithMouse {
            get {
                return ResourceManager.GetString("OverlayCloseWithMouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 영문 거래소를 이용하기.
        /// </summary>
        internal static string UseInvariantForTradeResults {
            get {
                return ResourceManager.GetString("UseInvariantForTradeResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 위키 설정.
        /// </summary>
        internal static string Wiki {
            get {
                return ResourceManager.GetString("Wiki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 위키 열기.
        /// </summary>
        internal static string Wiki_Key_Open {
            get {
                return ResourceManager.GetString("Wiki_Key_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 선호하는 위키를 선택하세요.
        /// </summary>
        internal static string Wiki_Preferred {
            get {
                return ResourceManager.GetString("Wiki_Preferred", resourceCulture);
            }
        }
    }
}
