//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sidekick.Modules.General.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GeneralResources_fr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeneralResources_fr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sidekick.Modules.General.Localization.GeneralResources.fr", typeof(GeneralResources_fr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fermer la fenêtre avec la touche Échapper.
        /// </summary>
        internal static string EscapeClosesOverlays {
            get {
                return ResourceManager.GetString("EscapeClosesOverlays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conserver la valeur de votre presse-papier (clipboard).
        /// </summary>
        internal static string General_RetainClipboard {
            get {
                return ResourceManager.GetString("General_RetainClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub Repository.
        /// </summary>
        internal static string GitHub_Repository {
            get {
                return ResourceManager.GetString("GitHub_Repository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fermer la fenêtre.
        /// </summary>
        internal static string Key_Close {
            get {
                return ResourceManager.GetString("Key_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechercher des items.
        /// </summary>
        internal static string Key_FindItems {
            get {
                return ResourceManager.GetString("Key_FindItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouvrir l&apos;item dans CraftOfExile.com.
        /// </summary>
        internal static string Key_Open_In_Craft_Of_Exile {
            get {
                return ResourceManager.GetString("Key_Open_In_Craft_Of_Exile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Langue de l&apos;interface.
        /// </summary>
        internal static string Language_UI {
            get {
                return ResourceManager.GetString("Language_UI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Roulette de souris pour naviguer dans l&apos;inventaire.
        /// </summary>
        internal static string MouseWheelNavigateStash {
            get {
                return ResourceManager.GetString("MouseWheelNavigateStash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation inversée dans l&apos;inventaire avec la roulette de souris.
        /// </summary>
        internal static string MouseWheelNavigateStashReverse {
            get {
                return ResourceManager.GetString("MouseWheelNavigateStashReverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site officiel.
        /// </summary>
        internal static string Official_Website {
            get {
                return ResourceManager.GetString("Official_Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouvrir le répertoire des configurations.
        /// </summary>
        internal static string Open_Settings_Folder {
            get {
                return ResourceManager.GetString("Open_Settings_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fermer la fenêtre sur un clic de la souris.
        /// </summary>
        internal static string OverlayCloseWithMouse {
            get {
                return ResourceManager.GetString("OverlayCloseWithMouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conserver la position des fenêtres. Si désactivé, les fenêtres seront centrées..
        /// </summary>
        internal static string SaveWindowPositions {
            get {
                return ResourceManager.GetString("SaveWindowPositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utiliser le site d&apos;échange anglais.
        /// </summary>
        internal static string UseInvariantForTradeResults {
            get {
                return ResourceManager.GetString("UseInvariantForTradeResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ce n&apos;est pas fiable pour certains items uniques, mais c&apos;est une solution de contournement..
        /// </summary>
        internal static string UseInvariantForTradeResultsTip {
            get {
                return ResourceManager.GetString("UseInvariantForTradeResultsTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurations Wiki.
        /// </summary>
        internal static string Wiki {
            get {
                return ResourceManager.GetString("Wiki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouvrir le Wiki.
        /// </summary>
        internal static string Wiki_Key_Open {
            get {
                return ResourceManager.GetString("Wiki_Key_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiki de préférence.
        /// </summary>
        internal static string Wiki_Preferred {
            get {
                return ResourceManager.GetString("Wiki_Preferred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        internal static string Zoom {
            get {
                return ResourceManager.GetString("Zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si le zoom est modifié, il est recommandé d&apos;ajuster également la taille des fenêtres..
        /// </summary>
        internal static string Zoom_Hint {
            get {
                return ResourceManager.GetString("Zoom_Hint", resourceCulture);
            }
        }
    }
}
